# Define Docker Compose version and services
version: "3.7"
services: 
# Define backend service
  backend:
    build: ./backend
    restart: always
    volumes: 
      - ./backend:/backend
      # - ./backend/node_modules:/backend/node_modules
    networks:
      - web-net
    environment:
      - TZ=Asia/Kolkata
    ports:
      - "5000:5000"
      - "5001:5001"

# Define frontend service
  frontend:
    build: ./frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/frontend
      # - ./frontend/node_modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING='true'
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - web-net

# Define nginx service for reverse proxy

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - frontend
      - backend
    networks:
      - web-net
    environment:
      - COMPOSE_HTTP_TIMEOUT=200

networks:
  web-net:
    driver: bridge
